# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/teststupid',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/teststupid',
                'lib_path': 'teststupid'},
  'syms': {'teststupid.core': {'teststupid.core.foo': ('core.html#foo', 'teststupid/core.py')}}}